import { Event, Task, Habit } from "./types";
import { format, subDays, addDays } from "date-fns";

const today = format(new Date(), "yyyy-MM-dd");
const yesterday = format(subDays(new Date(), 1), "yyyy-MM-dd");
const tomorrow = format(addDays(new Date(), 1), "yyyy-MM-dd");
const dayAfter = format(addDays(new Date(), 2), "yyyy-MM-dd");

export const MOCK_EVENTS: Event[] = [
  {
    id: "e1",
    title: "Reunião de equipe",
    categoryId: "trabalho",
    date: today,
    startTime: "09:00",
    endTime: "10:00",
    description: "Alinhamento semanal do time",
    recurrence: "semanal",
    confirmed: true,
  },
  {
    id: "e2",
    title: "Mentoria",
    categoryId: "estudos",
    date: today,
    startTime: "14:00",
    endTime: "15:00",
    description: "Sessão de mentoria com coach",
    recurrence: "nenhuma",
    confirmed: true,
  },
  {
    id: "e3",
    title: "Academia",
    categoryId: "academia",
    date: today,
    startTime: "07:00",
    endTime: "08:00",
    recurrence: "diaria",
    confirmed: true,
  },
  {
    id: "e4",
    title: "Almoço com família",
    categoryId: "familia",
    date: today,
    startTime: "12:00",
    endTime: "13:30",
    recurrence: "nenhuma",
    confirmed: true,
  },
  {
    id: "e5",
    title: "Revisão de finanças",
    categoryId: "financas",
    date: today,
    startTime: "18:00",
    endTime: "19:00",
    recurrence: "mensal",
    confirmed: false,
  },
  {
    id: "e6",
    title: "Projeto Pessoal - Sprint",
    categoryId: "pessoal",
    date: tomorrow,
    startTime: "20:00",
    endTime: "22:00",
    recurrence: "nenhuma",
    confirmed: true,
  },
  {
    id: "e7",
    title: "Consulta médica",
    categoryId: "saude",
    date: tomorrow,
    startTime: "10:00",
    endTime: "11:00",
    recurrence: "nenhuma",
    confirmed: true,
  },
  {
    id: "e8",
    title: "Planejamento de viagem",
    categoryId: "viagem",
    date: dayAfter,
    startTime: "15:00",
    endTime: "16:00",
    recurrence: "nenhuma",
    confirmed: false,
  },
  {
    id: "e9",
    title: "Aula de inglês",
    categoryId: "estudos",
    date: yesterday,
    startTime: "19:00",
    endTime: "20:00",
    recurrence: "semanal",
    confirmed: true,
  },
  {
    id: "e10",
    title: "Jantar especial",
    categoryId: "alimentacao",
    date: dayAfter,
    startTime: "19:30",
    endTime: "21:00",
    recurrence: "nenhuma",
    confirmed: true,
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: "t1",
    title: "Finalizar relatório mensal",
    description: "Consolidar dados de vendas e preparar apresentação",
    priority: "high",
    status: "in_progress",
    categoryId: "trabalho",
    dueDate: today,
    createdAt: yesterday,
  },
  {
    id: "t2",
    title: "Estudar TypeScript avançado",
    priority: "medium",
    status: "pending",
    categoryId: "estudos",
    dueDate: tomorrow,
    createdAt: today,
  },
  {
    id: "t3",
    title: "Pagar contas do mês",
    priority: "high",
    status: "completed",
    categoryId: "financas",
    dueDate: today,
    createdAt: yesterday,
  },
  {
    id: "t4",
    title: "Comprar ingredientes para a semana",
    priority: "low",
    status: "pending",
    categoryId: "alimentacao",
    dueDate: tomorrow,
    createdAt: today,
  },
  {
    id: "t5",
    title: "Revisar portfólio pessoal",
    priority: "medium",
    status: "pending",
    categoryId: "pessoal",
    dueDate: dayAfter,
    createdAt: today,
  },
  {
    id: "t6",
    title: "Agendar dentista",
    priority: "medium",
    status: "pending",
    categoryId: "saude",
    createdAt: today,
  },
];

export const MOCK_HABITS: Habit[] = [
  {
    id: "h1",
    name: "Meditação",
    categoryId: "saude",
    frequency: "diaria",
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    streak: 12,
    completedDates: [
      yesterday,
      format(subDays(new Date(), 2), "yyyy-MM-dd"),
      format(subDays(new Date(), 3), "yyyy-MM-dd"),
    ],
    createdAt: format(subDays(new Date(), 30), "yyyy-MM-dd"),
  },
  {
    id: "h2",
    name: "Leitura 30min",
    categoryId: "estudos",
    frequency: "diaria",
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    streak: 7,
    completedDates: [
      today,
      yesterday,
      format(subDays(new Date(), 2), "yyyy-MM-dd"),
    ],
    createdAt: format(subDays(new Date(), 20), "yyyy-MM-dd"),
  },
  {
    id: "h3",
    name: "Exercício físico",
    categoryId: "academia",
    frequency: "semanal",
    targetDays: [1, 3, 5],
    streak: 4,
    completedDates: [
      today,
      format(subDays(new Date(), 2), "yyyy-MM-dd"),
    ],
    createdAt: format(subDays(new Date(), 60), "yyyy-MM-dd"),
  },
  {
    id: "h4",
    name: "Beber 2L de água",
    categoryId: "saude",
    frequency: "diaria",
    targetDays: [0, 1, 2, 3, 4, 5, 6],
    streak: 21,
    completedDates: [
      today,
      yesterday,
      format(subDays(new Date(), 2), "yyyy-MM-dd"),
      format(subDays(new Date(), 3), "yyyy-MM-dd"),
    ],
    createdAt: format(subDays(new Date(), 45), "yyyy-MM-dd"),
  },
  {
    id: "h5",
    name: "Estudar código",
    categoryId: "estudos",
    frequency: "diaria",
    targetDays: [1, 2, 3, 4, 5],
    streak: 3,
    completedDates: [
      today,
      yesterday,
    ],
    createdAt: format(subDays(new Date(), 15), "yyyy-MM-dd"),
  },
];
